ALTER TYPE "StudentAttendanceStatus" ADD VALUE IF NOT EXISTS 'ABSENT_EXCUSED';
ALTER TYPE "StudentAttendanceStatus" ADD VALUE IF NOT EXISTS 'ABSENT_UNEXCUSED';
ALTER TYPE "StudentAttendanceStatus" ADD VALUE IF NOT EXISTS 'LEFT_EARLY';

ALTER TABLE "StudentAttendance"
ADD COLUMN IF NOT EXISTS "leftAt" TEXT,
ADD COLUMN IF NOT EXISTS "note" TEXT;
